// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6jOdsRozn3-1149c7fL3gwzbfKNuJ0ro',
    appId: '1:74870197691:web:d9cdc00e061b568d4f489e',
    messagingSenderId: '74870197691',
    projectId: 'crudflutterapp-20626',
    authDomain: 'crudflutterapp-20626.firebaseapp.com',
    storageBucket: 'crudflutterapp-20626.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmK8Pr9poWHvZCWtWfmmS4JtxOnUEoomQ',
    appId: '1:74870197691:android:276737f385838a0f4f489e',
    messagingSenderId: '74870197691',
    projectId: 'crudflutterapp-20626',
    storageBucket: 'crudflutterapp-20626.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkRC4s5iYz-8LHOf_1T-Ci3sukxzp31Es',
    appId: '1:74870197691:ios:4af7673e00b826894f489e',
    messagingSenderId: '74870197691',
    projectId: 'crudflutterapp-20626',
    storageBucket: 'crudflutterapp-20626.firebasestorage.app',
    iosBundleId: 'com.example.crudflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkRC4s5iYz-8LHOf_1T-Ci3sukxzp31Es',
    appId: '1:74870197691:ios:4af7673e00b826894f489e',
    messagingSenderId: '74870197691',
    projectId: 'crudflutterapp-20626',
    storageBucket: 'crudflutterapp-20626.firebasestorage.app',
    iosBundleId: 'com.example.crudflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6jOdsRozn3-1149c7fL3gwzbfKNuJ0ro',
    appId: '1:74870197691:web:a61595e742a285ab4f489e',
    messagingSenderId: '74870197691',
    projectId: 'crudflutterapp-20626',
    authDomain: 'crudflutterapp-20626.firebaseapp.com',
    storageBucket: 'crudflutterapp-20626.firebasestorage.app',
  );

}